### ISSUE TITLE
Xcode 8.3: Type Any does not conform to protocol Sequence

### ISSUE THREAD

**Issue by MartinSchultz** [miller-ms/MMSCameraViewController#1]
Since the recent Xcode 8.3 update the compiler throws the error:

/MMSCameraViewController/Classes/MMSCameraViewController.swift:448:42: Type '[Any]!!' does not conform to protocol 'Sequence'

```
for port in (connection as AnyObject).inputPorts { // <----- this line throws error
   if (port as! AVCaptureInputPort).mediaType == AVMediaTypeVideo {
       videoConnection = connection as! AVCaptureConnection
       break connectionloop
   }
}
```
Any idea how to solve this?

**Comment by MartinSchultz** [comment]
Ok, this fixes it:

for port in (connection as! AVCaptureConnection).inputPorts {
...

**Comment by miller-ms** [comment]
Awesome...thank you for the follow up.  I will change and update the repository.   Strange that it was not flagged earlier.
