### ISSUE TITLE
Unsupported Swift Version Error in Xcode 9

### ISSUE THREAD

**Issue by agupta3300** [miller-ms/MMSCameraViewController#2]
When using with Xcode 9. The following error occured.

The target “MMSCameraViewController” contains source code developed with Swift 2.x. Xcode 9 does not support building or migrating Swift 2.x targets.
Use Xcode 8.x to migrate the code to Swift 3.

**Comment by miller-ms** [comment]
Thanks you for bringing to my attention.  Application has been upgraded to swift 4 on Xcode 9.1.
