### ISSUE TITLE
Use of extraneous '&' error with Xcode 10 Beta

### ISSUE THREAD

**Issue by AlexFWulff** [miller-ms/MMSCameraViewController#3]
When including MMSCameraViewController in a project in Xcode 10 the project will not compile due to an error on line 720 of `MMSCamerViewController.swift`. The error is regarding the following line:

`case ("capturingStillImage", &CaptureStillImageContext):`

It reads:`Use of extraneous '&'`. Please advise.

**Comment by miller-ms** [comment]
Apple Xcode is often fairly buggy until around December after the production release.  Given my limited time, I cannot investigate ones related to beta versions.
